[package]
name = "vcs"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
pyo3 = { version = "0.21", features = ["auto-initialize"] }
clap = { version = "4.5", features = ["derive"] }
clib = { path = "../clib" }
